In [1]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
df=pd.read_csv('/content/gender_classification_v7.csv')
df

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female
...,...,...,...,...,...,...,...,...
4996,1,13.6,5.1,0,0,0,0,Female
4997,1,11.9,5.4,0,0,0,0,Female
4998,1,12.9,5.7,0,0,0,0,Female
4999,1,13.2,6.2,0,0,0,0,Female
5000,1,15.4,5.4,1,1,1,1,Male

In [4]:
df['gender']=df['gender'].map({'Male':0,'Female':1}).astype(int)

In [5]:
df

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,0
1,0,14.0,5.4,0,0,1,0,1
2,0,11.8,6.3,1,1,1,1,0
3,0,14.4,6.1,0,1,1,1,0
4,1,13.5,5.9,0,0,0,0,1
...,...,...,...,...,...,...,...,...
4996,1,13.6,5.1,0,0,0,0,1
4997,1,11.9,5.4,0,0,0,0,1
4998,1,12.9,5.7,0,0,0,0,1
4999,1,13.2,6.2,0,0,0,0,1
5000,1,15.4,5.4,1,1,1,1,0

In [9]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
x_train.shape

(4000, 7)

In [13]:
x_test.shape

(1001, 7)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
odd=np.arange(3,51,2)
odd

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49])

In [19]:
a=[]
for i in odd:
  p=KNeighborsClassifier(n_neighbors=i)
  p.fit(x_train,y_train)
  ans=p.predict(x_test)
  a.append(accuracy_score(y_test,ans))

a

[0.964035964035964,
 0.962037962037962,
 0.965034965034965,
 0.968031968031968,
 0.9660339660339661,
 0.967032967032967,
 0.9660339660339661,
 0.968031968031968,
 0.968031968031968,
 0.968031968031968,
 0.968031968031968,
 0.967032967032967,
 0.9660339660339661,
 0.965034965034965,
 0.964035964035964,
 0.965034965034965,
 0.965034965034965,
 0.964035964035964,
 0.964035964035964,
 0.964035964035964,
 0.964035964035964,
 0.964035964035964,
 0.965034965034965,
 0.964035964035964]

In [20]:
odd[np.argmax(a)]

np.int64(9)

In [23]:
reg=KNeighborsClassifier(n_neighbors=9)
reg.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

#train

In [24]:
ans_train=reg.predict(x_train)

In [25]:
confusion_matrix(y_train,ans_train)

array([[1934,   67],
       [  30, 1969]])

In [26]:
accuracy_score(y_train,ans_train)

0.97575

In [27]:
print(classification_report(y_train,ans_train))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98      2001
           1       0.97      0.98      0.98      1999

    accuracy                           0.98      4000
   macro avg       0.98      0.98      0.98      4000
weighted avg       0.98      0.98      0.98      4000

#test

In [28]:
ans_test=reg.predict(x_test)

In [30]:
confusion_matrix(y_test,ans_test)

array([[476,  23],
       [  9, 493]])

In [31]:
accuracy_score(y_test,ans_test)

0.968031968031968

In [32]:
print(classification_report(y_test,ans_test))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       499
           1       0.96      0.98      0.97       502

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001

#check

In [33]:
x_train.columns

Index(['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long'],
      dtype='object')

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [39]:
print(reg.predict([[1 , 12.2 , 10.2 , 1.4 , 4.5 , 5.6 , 5.0]])[0])

0

In [40]:
if reg.predict([[1 , 12.2 , 10.2 , 1.4 , 4.5 , 5.6 , 5.0]])[0]==0:
  print('male')
else:
  print('female')

male

In [42]:
import pickle
with open('Gender.pkl','wb') as f:
  pickle.dump(reg,f)

In [43]:
with open('/content/Gender.pkl','rb') as f:
  m=pickle.load(f)

In [44]:
m.predict([[1 , 12.2 , 10.2 , 1.4 , 4.5 , 5.6 , 5.0]])

array([0])